apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: VirtualDeploymentBinding
metadata:
  name: ms-redis-ms-redis-binding
  namespace: default
  annotations:
    servicemesh.oci.oracle.com/proxy-log-level: debug
spec:
  virtualDeployment:
    id: >-
      ocid1.meshvirtualdeployment.oc1.iad.amaaaaaaihuwreyaybjeh3u4smp6giuctvi464klyl2i7oak56saflbnix7q
  target:
    service:
      ref:
        name: redis
        namespace: default
---
apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: IngressGatewayDeployment
metadata:
  name: redis-ingress-gateway-binding
  annotations:
    servicemesh.oci.oracle.com/proxy-log-level: debug
spec:
  ingressGateway:
    id: >-
      ocid1.meshingressgateway.oc1.iad.amaaaaaaihuwreya2dobvbj62nx7jqdk3hnr6h3bgsmgmprypec5lvqs5zva
  deployment:
    autoscaling:
      minPods: 1
      maxPods: 1
  ports:
    - protocol: TCP
      serviceport: 6379
      port: 6379
  service:
    type: LoadBalancer
