apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    name: redis
    servicemesh.oci.oracle.com/ingress-gateway-deployment: redis-ingress-gateway-binding
  type: NodePort
  ports:
  - port: 6379
    nodePort: 32511
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis
    component: cache
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        args: ["--requirepass", "$(REDIS_PASS)"]
        ports:
        - containerPort: 6379
          name: redis
        env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PASS
---
